version: '3'
services:

  server:
    build: server
    ports:
      - 8080:8080
    networks:
      - backend

  database:
    image: mysql
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: super_secret_mysql_root_password
    expose:
      - '3306'
    volumes:
      - /var/lib/mysql

networks:
  backend:
