version: '3.2'
services:

  server:
    build: server
    restart: always
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - backend
    depends_on:
      - database

  # A hand-coded second server to show that we can scale sideways.
  server2:
    build: server
    restart: always
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - backend
    depends_on:
      - database

  database:
    image: mysql
    restart: always
    command: --init-file /init/init.sql
    networks:
      - backend
    environment:
      # MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_HOST: '%'
    expose:
      - '3306'
    volumes:
      - /var/lib/mysql
      - ./init.sql:/init/init.sql


networks:
  backend:
